hipogram/posts/urls.py
from django.urls import path
from .views import post_list_view
from . import views

app_name = "posts"

urlpatterns = [
    path("", post_list_view, name="list"),
    path("uploadpost/", views.upload , name='upload_post'),
    path("user/<str:pathUsername>/", views.filter_username, name='filter_by_username'),
    path("deletepost/<int:id>", views.delete, name='delete'),
    path("updatepost/<int:id>", views.update, name='update'),
    path("updatepost/<int:id>/confirm", views.updateConfirm, name='updateConfirm')

]

hipogram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("hipogram.posts.urls", namespace="posts")),
    path("", include("hipogram.users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hipogram/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import signup_view

app_name = "users"

urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

hipogram/posts/models.py
from django.db import models


class Post(models.Model):
    image = models.ImageField()
    text = models.TextField()
    created_by = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    creation_datetime = models.DateTimeField(auto_now_add=True)

hipogram/posts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post


def post_list_view(request):

    posts = Post.objects.all().order_by("-creation_datetime")

    #Pagination işlemleri.
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    return render(request, "post_list.html", {'posts': posts})


#Yeni fotoğraf yükleme işlemi.
def upload(request):
    # Giriş yapmayan veya doğrulanmamış kullanıcı login sayfasına yönlendirilir.
    if not request.user.is_authenticated or request.user.is_anonymous:
        return redirect('http://127.0.0.1:8000/login')


    if request.method == 'POST':
        post = request.FILES['post']
        text = request.POST['text-area']

        posts = Post.objects.create(image = post, created_by = request.user, text = text)
        if posts:
            messages.success(request, "POST uploaded.")

    return render(request, 'upload_photo.html')


#Kullanıcının kendi postlarını filtreleme işlemi.
def filter_username(request, pathUsername):
    print("Goruntulenmek istenen kullanici: ", pathUsername)
    print("Goruntulenen kullanici: ", request.user)


    if not request.user.is_authenticated or request.user.is_anonymous:
        return redirect('http://127.0.0.1:8000/login')

    #Giriş yapmayan veya doğrulanmamış kullanıcı adına göre filtrelemek isterse login sayfasına yönlendirilir.

    posts = Post.objects.filter(created_by = request.user).order_by("-creation_datetime")

    """
    posts = Post.objects.filter(created_by = pathUsername).order_by("-creation_datetime")
    created_by = pathUsername olmalıydı ancak key = str olmadığından buna bir çözüm bulamadım,
    kullanıcı sadece kendi fotoğraflarını filtreleyebiliyor.
    """

    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'filter_username.html', {'posts': posts})


#Kullanıcı username ile filtreleme yaptıktan sonra
#kendi postlarından istediğini silebilir.
def delete(request, id):

    posts = Post.objects.filter(created_by = request.user, id = id).delete()
    newPosts = Post.objects.all().order_by("-creation_datetime")

    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "post_list.html", {'posts': newPosts})


def update(request, id):

    post = Post.objects.filter(created_by=request.user, id=id)

    return render(request, 'update_photo.html', {'posts': post})


def updateConfirm(request, id):
    newPosts = Post.objects.all().order_by("-creation_datetime")


    post = Post.objects.filter(created_by = request.user, id = id).update(text = "Update işlemini dynamic yapamadım,"
                                                                                 "input valueyi almaya çalıştığımda None dönüyor.")

    if post:
            messages.success(request, "Updated successfully..")

    return render(request, 'post_list.html', {'posts': newPosts})

hipogram/users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {"form": form})

hipogram/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>{% block title %}Hipogram{% endblock %}</title>
    <!---------- CSS ----------->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    {% block css %}{% endblock %}
    <!-------------------------->
  </head>
  <body>
    {% block body %}
      {% include "navbar.html" %}
      <div class="container-fluid mt-5">
        {% block content %}{% endblock %}
      </div>
    {% endblock body %}
    <!------- JavaScript ------->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block js %}{% endblock %}
    <!-------------------------->
  </body>


{% if posts.has_other_pages %}
  <div style="display: flex; justify-content: center;">
  <ul class="pagination" >
    {% if posts.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  </div>
{% endif %}

</html>

hipogram/core/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand ml-5" href="{% url "posts:list" %}">Hipogram</a>
  <!-- edited -->
  <a class="navbar-brand ml-5" href="{% url "posts:upload_post" %}">Share a Photo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse mr-5" id="navbarNav">
    {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="{% url "users:logout" %}">Log out</a>
          </div>
        </li>
      </ul>
    {% else %}
      <form class="form-inline ml-auto">
        <a href="{% url "users:login" %}" class="btn btn-outline-light">Log in</a>
        <a href="{% url "users:signup" %}" class="btn btn-light ml-2">Sign up</a>
      </form>
    {% endif %}
  </div>
</nav>

hipogram/core/templates/upload_photo.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <form
      class="container"
      method="POST"
      action=""
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <h1 class="text-center text-primary">Upload Post</h1>
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Post</label>
        <input
          type="file"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          name="post"
        />
      </div>

    <br>

    <textarea name="text-area" rows="4" cols="50" placeholder="Entry here."></textarea>
      <button type="submit" class="btn btn-primary">Share</button>
      </form>
  </div>
{% endblock content %}

hipogram/posts/templates/filter_username.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <form
      class="container"
      method="POST"
      action=""
      enctype="multipart/form-data"
    >
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
          <a href="/user/{{post.created_by.username}}"><h2 class="card-title">{{ post.created_by.username }}</h2></a>
          <img class="img-fluid mb-3" style="max-height:400px" src="{{ post.image.url }}"/>
          <p class="card-text">{{ post.text }}</p>
          <a href="/deletepost/{{post.id}}" style="color: red;">Delete</a>
          <a href="/updatepost/{{post.id}}" style="color: blue;">Update</a>
        </div>
        <small class="card-footer text-muted text-right p-2">{{ post.creation_datetime|date:"H:i - d.m.Y" }}</small>
      </div>
    {% endfor %}
    </form>
  </div>



{% endblock content %}

hipogram/posts/templates/post_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
          <a href="/user/{{post.created_by.username}}"><h2 class="card-title" name="username">{{ post.created_by.username }}</h2></a>
          <img class="img-fluid mb-3" style="max-height:400px" src="{{ post.image.url }}"/>
          <p class="card-text">{{ post.text }}</p>
        </div>
        <small class="card-footer text-muted text-right p-2">{{ post.creation_datetime|date:"H:i - d.m.Y" }}</small>
      </div>
    {% endfor %}
  </div>



{% endblock content %}

hipogram/posts/templates/update_photo.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <form
      name="updateForm"
      class="container"
      method="POST"
      action=""
      enctype="multipart/form-data"
    >
      {% csrf_token %}
    {% for post in posts %}
      <div class="card mb-3">
        <div class="card-body">
          <a href="/user/{{post.created_by.username}}"><h2 class="card-title">{{ post.created_by.username }}</h2></a>
          <img class="img-fluid mb-3" style="max-height:400px" src="{{ post.image.url }}"/>
          <p class="card-text">{{ post.text }}</p>
        </div>
        <input type="text" maxlength="100" placeholder="This will be your new description, entry here." size="100">
        <a href="/updatepost/{{post.id}}/confirm" style="color: blue;">Confirm</a>
        <small class="card-footer text-muted text-right p-2">{{ post.creation_datetime|date:"H:i - d.m.Y" }}</small>
      </div>
    {% endfor %}
    </form>
  </div>

{% endblock content %}

hipogram/users/templates/form_card.html
{% load crispy_forms_tags %}

<div class="row justify-content-center">
  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title mb-5">{{ title }}</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-primary btn-block">{{ button_text }}</button>
        </form>
      </div>
    </div>
  </div>
</div>

hipogram/users/templates/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
  {% include "form_card.html" with title="Log in" button_text="Log in" %}
  <div class="text-center text-muted mt-1">
    Do not have an account? <a href="{% url "users:signup" %}">Sign up</a>
  </div>
{% endblock content %}

hipogram/users/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
  {% include "form_card.html" with title="Sign up" button_text="Sign up" %}
  <div class="text-center text-muted mt-1">
    Already have an account? <a href="{% url "users:login" %}">Log in</a>
  </div>
{% endblock content %}